#!/bin/sh

rm -f /tmp/luci-indexcache /tmp/luci-modulecache/* 2>/dev/null || true
[ -x /etc/init.d/forkop-analyzer ] && /etc/init.d/forkop-analyzer restart >/dev/null 2>&1 || true
[ -x /etc/init.d/rpcd ] && /etc/init.d/rpcd restart >/dev/null 2>&1 || true

exit 0
