include $(TOPDIR)/rules.mk

PKG_NAME:=luci-app-forkop-analyzer
PKG_VERSION:=0.2.0
PKG_RELEASE:=1

PKG_MAINTAINER:=MaksSt
PKG_LICENSE:=MIT

LUCI_TITLE:=LuCI support for Forkop Analyzer
LUCI_DEPENDS:=+forkop-analyzer
LUCI_PKGARCH:=all

include $(TOPDIR)/feeds/luci/luci.mk

# call BuildPackage - OpenWrt buildroot signature
